# Generated by Django 5.2.7 on 2025-10-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio', models.CharField(max_length=10)),
                ('fecha_evento', models.DateField()),
                ('ubicacion', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=20)),
                ('paterno', models.CharField(max_length=20)),
                ('materno', models.CharField(max_length=20)),
                ('observacion0', models.CharField(max_length=20)),
                ('pago', models.CharField(max_length=1)),
                ('fecha_autorizacion', models.DateField()),
                ('hora_autorizacion', models.TimeField()),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
            ],
        ),
    ]
