# Generated by Django 5.2.7 on 2025-10-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitado',
            old_name='observacion0',
            new_name='observacion',
        ),
    ]
