# Generated by Django 5.2.7 on 2025-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_observacion0_invitado_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='fecha_autorizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='hora_autorizacion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
